//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monk
    {
        public int Id { get; set; }
        public string Cid { get; set; }
        public string Religion { get; set; }
        public string Blood { get; set; }
        public string SWno { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Bdate { get; set; }
        public string Age { get; set; }
        public string Pno { get; set; }
        public string Htown { get; set; }
        public string Tribe { get; set; }
        public string Bparent { get; set; }
        public string FFname { get; set; }
        public string FLname { get; set; }
        public string Fage { get; set; }
        public string Ftribe { get; set; }
        public string MFname { get; set; }
        public string MLname { get; set; }
        public string Mage { get; set; }
        public string Mtribe { get; set; }
        public string Sib_num { get; set; }
        public string Sib_ord { get; set; }
        public string Sib_men { get; set; }
        public string Sib_women { get; set; }
    }
}
